AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB Table for Aurora Restore Audit Trail'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Environment for the Aurora Restore Pipeline

  TableName:
    Type: String
    Default: aurora-restore-audit
    Description: Name of the DynamoDB table

  ReadCapacityUnits:
    Type: Number
    Default: 5
    Description: Read capacity units for the table

  WriteCapacityUnits:
    Type: Number
    Default: 5
    Description: Write capacity units for the table

Resources:
  # DynamoDB Table
  AuditTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${TableName}-${Environment}
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacityUnits
        WriteCapacityUnits: !Ref WriteCapacityUnits
      AttributeDefinitions:
        - AttributeName: operation_id
          AttributeType: S
        - AttributeName: step
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: operation_id
          KeyType: HASH
        - AttributeName: step
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: TimestampIndex
          KeySchema:
            - AttributeName: timestamp
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref ReadCapacityUnits
            WriteCapacityUnits: !Ref WriteCapacityUnits
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: AuroraRestore

  # DynamoDB IAM Role
  DynamoDBRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: AuroraRestoreDynamoDBPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                Resource:
                  - !GetAtt AuditTable.Arn
                  - !Sub ${AuditTable.Arn}/index/*

Outputs:
  TableArn:
    Description: ARN of the DynamoDB Table
    Value: !GetAtt AuditTable.Arn
    Export:
      Name: !Sub ${AWS::StackName}-TableArn

  TableName:
    Description: Name of the DynamoDB Table
    Value: !Ref AuditTable
    Export:
      Name: !Sub ${AWS::StackName}-TableName

  DynamoDBRoleArn:
    Description: ARN of the DynamoDB IAM Role
    Value: !GetAtt DynamoDBRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-DynamoDBRoleArn 