AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM roles and policies for Aurora Restore Pipeline Lambda functions'

Resources:
  AuroraRestoreLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-aurora-restore-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: AuroraRestoreLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${AWS::StackName}-aurora-restore-state
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${AWS::StackName}-aurora-restore-state-index
              - Effect: Allow
                Action:
                  - rds:DescribeDBClusterSnapshots
                  - rds:CopyDBClusterSnapshot
                  - rds:DeleteDBClusterSnapshot
                  - rds:DescribeDBClusters
                  - rds:DeleteDBCluster
                  - rds:RestoreDBClusterFromSnapshot
                  - rds:ModifyDBCluster
                Resource: '*'
              - Effect: Allow
                Action:
                  - events:PutRule
                  - events:PutTargets
                  - events:DeleteRule
                  - events:RemoveTargets
                  - events:DisableRule
                  - events:EnableRule
                Resource: !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/aurora-restore-*
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: '*'
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/aurora-restore/*
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:aurora-restore-*
      Tags:
        - Key: Application
          Value: AuroraRestore
        - Key: Environment
          Value: !Ref Environment

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Environment for the Aurora Restore Pipeline

Outputs:
  LambdaRoleArn:
    Description: ARN of the Lambda execution role
    Value: !GetAtt AuroraRestoreLambdaRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-LambdaRoleArn 