AWSTemplateFormatVersion: '2010-09-09'
Description: 'Step Functions State Machine for Aurora Restore Pipeline'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Environment for the Aurora Restore Pipeline

  SnapshotCheckFunctionArn:
    Type: String
    Description: ARN of the Snapshot Check Lambda Function

  CopySnapshotFunctionArn:
    Type: String
    Description: ARN of the Copy Snapshot Lambda Function

  CheckCopyStatusFunctionArn:
    Type: String
    Description: ARN of the Check Copy Status Lambda Function

  DeleteRDSFunctionArn:
    Type: String
    Description: ARN of the Delete RDS Lambda Function

  RestoreSnapshotFunctionArn:
    Type: String
    Description: ARN of the Restore Snapshot Lambda Function

  CheckRestoreStatusFunctionArn:
    Type: String
    Description: ARN of the Check Restore Status Lambda Function

  SetupDBUsersFunctionArn:
    Type: String
    Description: ARN of the Setup DB Users Lambda Function

  ArchiveSnapshotFunctionArn:
    Type: String
    Description: ARN of the Archive Snapshot Lambda Function

  SNSNotificationFunctionArn:
    Type: String
    Description: ARN of the SNS Notification Lambda Function

Resources:
  # Step Functions Role
  StepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AuroraRestoreStepFunctionsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Ref SnapshotCheckFunctionArn
                  - !Ref CopySnapshotFunctionArn
                  - !Ref CheckCopyStatusFunctionArn
                  - !Ref DeleteRDSFunctionArn
                  - !Ref RestoreSnapshotFunctionArn
                  - !Ref CheckRestoreStatusFunctionArn
                  - !Ref SetupDBUsersFunctionArn
                  - !Ref ArchiveSnapshotFunctionArn
                  - !Ref SNSNotificationFunctionArn

  # State Machine
  AuroraRestoreStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub aurora-restore-pipeline-${Environment}
      RoleArn: !GetAtt StepFunctionsRole.Arn
      Definition:
        StartAt: SnapshotCheck
        States:
          SnapshotCheck:
            Type: Task
            Resource: !Ref SnapshotCheckFunctionArn
            Next: CopySnapshot
            Retry:
              - ErrorEquals:
                  - States.ALL
                IntervalSeconds: 2
                MaxAttempts: 3
                BackoffRate: 2.0
            Catch:
              - ErrorEquals:
                  - States.ALL
                Next: NotifyFailure
                ResultPath: $.error

          CopySnapshot:
            Type: Task
            Resource: !Ref CopySnapshotFunctionArn
            Next: CheckCopyStatus
            Retry:
              - ErrorEquals:
                  - States.ALL
                IntervalSeconds: 2
                MaxAttempts: 3
                BackoffRate: 2.0
            Catch:
              - ErrorEquals:
                  - States.ALL
                Next: NotifyFailure
                ResultPath: $.error

          CheckCopyStatus:
            Type: Task
            Resource: !Ref CheckCopyStatusFunctionArn
            Next: IsCopyComplete
            Retry:
              - ErrorEquals:
                  - States.ALL
                IntervalSeconds: 2
                MaxAttempts: 3
                BackoffRate: 2.0
            Catch:
              - ErrorEquals:
                  - States.ALL
                Next: NotifyFailure
                ResultPath: $.error

          IsCopyComplete:
            Type: Choice
            Choices:
              - Variable: "$.copy_status"
                StringEquals: "available"
                Next: DeleteRDS
            Default: WaitForCopy
            Comment: Check if snapshot copy is complete

          WaitForCopy:
            Type: Wait
            Seconds: 30
            Next: CheckCopyStatus

          DeleteRDS:
            Type: Task
            Resource: !Ref DeleteRDSFunctionArn
            Next: RestoreSnapshot
            Retry:
              - ErrorEquals:
                  - States.ALL
                IntervalSeconds: 2
                MaxAttempts: 3
                BackoffRate: 2.0
            Catch:
              - ErrorEquals:
                  - States.ALL
                Next: NotifyFailure
                ResultPath: $.error

          RestoreSnapshot:
            Type: Task
            Resource: !Ref RestoreSnapshotFunctionArn
            Next: CheckRestoreStatus
            Retry:
              - ErrorEquals:
                  - States.ALL
                IntervalSeconds: 2
                MaxAttempts: 3
                BackoffRate: 2.0
            Catch:
              - ErrorEquals:
                  - States.ALL
                Next: NotifyFailure
                ResultPath: $.error

          CheckRestoreStatus:
            Type: Task
            Resource: !Ref CheckRestoreStatusFunctionArn
            Next: IsRestoreComplete
            Retry:
              - ErrorEquals:
                  - States.ALL
                IntervalSeconds: 2
                MaxAttempts: 3
                BackoffRate: 2.0
            Catch:
              - ErrorEquals:
                  - States.ALL
                Next: NotifyFailure
                ResultPath: $.error

          IsRestoreComplete:
            Type: Choice
            Choices:
              - Variable: "$.restore_status"
                StringEquals: "available"
                Next: SetupDBUsers
            Default: WaitForRestore
            Comment: Check if restore is complete

          WaitForRestore:
            Type: Wait
            Seconds: 30
            Next: CheckRestoreStatus

          SetupDBUsers:
            Type: Task
            Resource: !Ref SetupDBUsersFunctionArn
            Next: ArchiveSnapshot
            Retry:
              - ErrorEquals:
                  - States.ALL
                IntervalSeconds: 2
                MaxAttempts: 3
                BackoffRate: 2.0
            Catch:
              - ErrorEquals:
                  - States.ALL
                Next: NotifyFailure
                ResultPath: $.error

          ArchiveSnapshot:
            Type: Task
            Resource: !Ref ArchiveSnapshotFunctionArn
            Next: NotifySuccess
            Retry:
              - ErrorEquals:
                  - States.ALL
                IntervalSeconds: 2
                MaxAttempts: 3
                BackoffRate: 2.0
            Catch:
              - ErrorEquals:
                  - States.ALL
                Next: NotifyFailure
                ResultPath: $.error

          NotifySuccess:
            Type: Task
            Resource: !Ref SNSNotificationFunctionArn
            End: true
            Retry:
              - ErrorEquals:
                  - States.ALL
                IntervalSeconds: 2
                MaxAttempts: 3
                BackoffRate: 2.0
            Catch:
              - ErrorEquals:
                  - States.ALL
                Next: NotifyFailure
                ResultPath: $.error

          NotifyFailure:
            Type: Task
            Resource: !Ref SNSNotificationFunctionArn
            End: true
            Retry:
              - ErrorEquals:
                  - States.ALL
                IntervalSeconds: 2
                MaxAttempts: 3
                BackoffRate: 2.0

Outputs:
  StateMachineArn:
    Description: ARN of the Aurora Restore State Machine
    Value: !GetAtt AuroraRestoreStateMachine.Arn
    Export:
      Name: !Sub ${AWS::StackName}-StateMachineArn

  StateMachineName:
    Description: Name of the Aurora Restore State Machine
    Value: !Ref AuroraRestoreStateMachine
    Export:
      Name: !Sub ${AWS::StackName}-StateMachineName 